name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [deploy2]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages - ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      #setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build image client and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./client
          file: ./client/Dockerfile.prod
          tags: ghcr.io/malizia-g/client-ci:0.1
          push: true

      - name: Build image server and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./server
          file: ./server/Dockerfile.prod
          tags: ghcr.io/malizia-g/server-ci:0.2
          push: true
         
      #     # build on feature branches, push only on main branch
      #     push: ${{ github.ref == 'refs/heads/main' }}
      #
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}